#!/usr/bin/python

# columns that need to be renamed go here

column_renames = {
	'RunId' : 'runid' ,
	'RunFolder' : 'RunFolder' ,
	'SampleNumber' : 'Snumber' ,
	'Name' : 'id' ,
	'Assay' : 'Experiment_name' ,
	'Input' : 'input' ,
	'Source' : 'source' ,
	'ExpectedCN' : 'MT' ,
	'Type' : 'type' ,
	'Tool' : 'Tool' ,
	'Environment' : 'Environment' ,
	'SamplePlate' : 'SamplePlate' ,
	'SampleWell' : 'SampleWell' ,
	'I7IndexID' : 'I7IndexID' ,
	'Index' : 'Index' ,
	'StandardGroup' : 'StandardGroup' ,
	'Batch' : 'Batch' ,
	'CheckoutNumber' : 'CheckoutNumber' ,
	'ngPerRxn' : 'ngPerRxn' ,
	'PhixFraction' : 'PhixFraction' ,
	'ProjectVersion' : 'ProjectVersion' ,
	'ClustersRaw' : 'ClustersRaw' ,
	'ClustersPF' : 'ClustersPF' ,
	'RawReads' : 'total_reads' ,
	'TrimmedReads' : 'TrimmedReads' ,
	'TrimmedFilteredReads' : 'total_seq' ,
	'TotalMappedReads' : 'TotalMappedReads' ,
	'TotalTargetReads' : 'gene_seq' ,
	'PhiXReads' : 'PhiXReads' ,
	'PrimerArtifacts' : 'PrimerArtifacts' ,
	'Other' : 'Other' ,
	'OTA' : 'OTA' ,
	'TargetWTReads' : 'wild_type' ,
	'Chr' : 'Chr' ,
	'Start' : 'Start' ,
	'Sequence' : 'Sequence' ,
	'Count' : 'Count' ,
	'MutationName' : 'Mutation' ,
	'MTcount' : 'mutant_reads' ,
	'FLAGS' : 'FLAGS' ,
	'QC' : 'Count_QC' ,
	'bias_adj' : 'bias_adj',
	'adj_mutant_reads' : 'adj_mutant_reads',
	'DetectionThreshold' : 'DetectionThreshold',
	'DetectCall' : 'p_call' ,
	'FitCN' : 'p_fit' ,
	'FitCN_lower' : 'p_lower' ,
	'FitCN_upper' : 'p_upper' ,
	'GEq' : 'GEq' ,
	'GEq_lower' : 'GEq_lower' ,
	'GEq_upper' : 'GEq_upper' ,
	'LLoQ' : 'LLoQ'
}
