#!/usr/bin/python

# Status Flags		
NGS_RUN_DOES_NOT_EXIST     = "NGS_RUN_DOES_NOT_EXIST"
NGS_RUN_PENDING            = "NGS_RUN_PENDING"
NGS_RUN_COMPLETE           = "NGS_RUN_COMPLETE"
NGS_ANALYSIS_IN_PROGRESS   = "NGS_ANALYSIS_IN_PROGRESS"
NGS_CLIA_REVIEW            = "NGS_CLIA_REVIEW"
NGS_ANALYSIS_DELETED       = "NGS_ANALYSIS_DELETED"
NGS_ANALYSIS_COMPLETE      = "NGS_ANALYSIS_COMPLETE"
NGS_ANALYSIS_ERROR         = "NGS_ANALYSIS_ERROR"
NGS_UPLOADED_TO_TROVABASE  = "NGS_UPLOADED_TO_TROVABASE"
NGS_TROVABASE_UPLOAD_ERROR = "NGS_TROVABASE_UPLOAD_ERROR"
NGS_ARCHIVE_ERROR          = "NGS_ARCHIVE_ERROR"
NGS_ARCHIVE_COMPLETE       = "NGS_ARCHIVE_COMPLETE"
NGS_SAMPLESHEET_ERROR      = "NGS_SAMPLESHEET_ERROR"
